apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260610-234620-0zj4o74ajky0-service
spec:
  selector:
    app: enterprise-system-20260610-234620-0zj4o74ajky0
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
